### ISSUE TITLE
UI Expansion request

### ISSUE THREAD

**Issue by NicBeans** [francoisrob/cli_youtube#1]
It be real cool if we could see the video creator/duration/release date in the listings. as far as i know all these attributes should be available via ytcc, but seeing as you want to move to a different implementation I thought I'd throw out the request ahead of time. 
![image](https://user-images.githubusercontent.com/102036624/231678077-529668e9-0c3e-4139-bdd9-9d2da072cc68.png)
This would be a very basic example of the desired outputs.

**Comment by NicBeans** [comment]
Loving the new UI changes! Any chance for a "Video duration" column? If its not going to be a 5 min fix, perfectly cool, i can add one manually later and open a PR. Huge improvements already

**Comment by francoisrob** [comment]
Im going to rewrite the display function to take into account terminal sizes and resizing. At the moment the columns are fixed value sizes.
