### ISSUE TITLE
Scrolling off screen

### ISSUE THREAD

**Issue by NicBeans** [francoisrob/cli_youtube#2]
Loving the new UI changes. However, theyve presented a new issue. you can scroll off the bottom of the terminal without it scrolling with. 
![image](https://user-images.githubusercontent.com/102036624/231736478-828fab8a-4299-4d02-a4d4-211e58626fe0.png)
My scrollbar is currently at the very bottom of the list, below the last entry. if i keep scrolling down i eventually make it back to the top of the list. I can select videos off screen to play them. Pagination seems like a possible fix, else if, possible some form of scrolling mechanic? Let me know if you need code input on this, quite busy at the moment, so my submissions might come in late.

**Comment by francoisrob** [comment]
I am aware of this issue. I have to do some research on how to enable scrolling with curses when the list is bigger than the terminal rows
